In [27]:
import pandas as pd
import numpy as np

In [28]:
name = ['x', 'y','z']
filePath = '/Users/tingtingx/Documents/CEG4/SEM1/CG3002/ML_Code/HMP_Dataset/Brush_teeth/Accelerometer-2011-04-11-13-28-18-brush_teeth-f1.txt'
#replace the filepath

In [35]:
df = pd.read_table(filePath, delim_whitespace=True,header =None,
                names=name)
df.tail()

       x   y   z
2162  23  41  44
2163  23  42  44
2164  23  42  44
2165  22  40  43
2166  20  44  46

In [38]:
x=df.values

In [41]:
segment = []
for i in range(int(len(x)/100)):
    segment.append(x[i*100:((i*100)+(200)),0:])
segment[1]

array([[23, 49, 37],
       [24, 49, 37],
       [22, 51, 38],
       [23, 51, 38],
       [22, 51, 38],
       [22, 49, 38],
       [20, 51, 38],
       [20, 49, 37],
       [21, 50, 37],
       [22, 49, 38],
       [23, 49, 37],
       [24, 50, 38],
       [24, 50, 37],
       [25, 50, 38],
       [25, 49, 37],
       [24, 51, 37],
       [23, 50, 36],
       [20, 54, 34],
       [21, 50, 34],
       [21, 50, 35],
       [22, 51, 34],
       [23, 50, 35],
       [23, 49, 35],
       [22, 49, 35],
       [23, 50, 34],
       [20, 50, 35],
       [20, 50, 35],
       [19, 50, 36],
       [19, 50, 35],
       [19, 51, 36],
       [21, 50, 36],
       [22, 51, 36],
       [25, 52, 35],
       [25, 52, 35],
       [26, 51, 34],
       [25, 51, 35],
       [23, 51, 35],
       [21, 51, 35],
       [20, 51, 35],
       [19, 50, 36],
       [19, 50, 36],
       [20, 50, 35],
       [21, 50, 35],
       [21, 50, 36],
       [24, 50, 37],
       [24, 51, 36],
       [26, 52, 38],
       [25, 52, 37],
       [27, 51, 37],
       [26, 51, 36],
       [26, 51, 36],
       [23, 51, 35],
       [23, 51, 36],
       [22, 51, 35],
       [22, 52, 35],
       [22, 50, 35],
       [20, 50, 35],
       [21, 49, 36],
       [20, 50, 36],
       [20, 50, 35],
       [21, 50, 36],
       [22, 48, 36],
       [21, 51, 35],
       [18, 52, 36],
       [18, 48, 37],
       [19, 50, 36],
       [22, 50, 36],
       [24, 50, 36],
       [24, 51, 35],
       [25, 52, 35],
       [23, 52, 36],
       [24, 51, 36],
       [24, 51, 36],
       [25, 52, 36],
       [25, 52, 36],
       [23, 52, 36],
       [24, 52, 36],
       [24, 51, 35],
       [25, 52, 34],
       [24, 53, 34],
       [24, 51, 34],
       [23, 52, 33],
       [23, 52, 32],
       [25, 53, 32],
       [24, 50, 31],
       [26, 50, 32],
       [25, 51, 30],
       [25, 52, 30],
       [26, 51, 32],
       [26, 51, 31],
       [26, 52, 31],
       [27, 51, 30],
       [26, 52, 29],
       [25, 51, 30],
       [24, 52, 29],
       [25, 51, 29],
       [25, 50, 31],
       [25, 50, 29],
       [25, 52, 30],
       [26, 51, 31],
       [26, 49, 31],
       [27, 50, 32],
       [26, 51, 31],
       [25, 51, 32],
       [23, 52, 32],
       [21, 53, 33],
       [21, 52, 32],
       [22, 53, 31],
       [21, 53, 31],
       [21, 52, 31],
       [19, 52, 29],
       [17, 52, 31],
       [17, 52, 29],
       [16, 50, 31],
       [18, 50, 30],
       [21, 51, 32],
       [22, 54, 33],
       [24, 53, 34],
       [25, 52, 36],
       [26, 53, 36],
       [26, 55, 36],
       [27, 49, 38],
       [27, 50, 35],
       [28, 51, 37],
       [26, 51, 34],
       [25, 51, 34],
       [27, 52, 33],
       [27, 54, 33],
       [27, 55, 32],
       [30, 54, 36],
       [30, 46, 34],
       [29, 44, 30],
       [33, 33, 36],
       [33, 44, 37],
       [33, 53, 32],
       [26, 63, 25],
       [23, 62, 22],
       [30, 40, 28],
       [25, 31, 36],
       [29, 53, 41],
       [32, 61, 30],
       [32, 63, 21],
       [25, 54, 25],
       [27, 34, 31],
       [28, 53, 41],
       [33, 53, 35],
       [29, 63, 25],
       [29, 57, 20],
       [31, 38, 25],
       [27, 29, 39],
       [30, 47, 42],
       [27, 63, 28],
       [28, 63, 20],
       [26, 49, 26],
       [29, 40, 34],
       [28, 28, 44],
       [29, 46, 43],
       [28, 63, 24],
       [33, 62, 22],
       [29, 41, 29],
       [30, 28, 39],
       [25, 49, 44],
       [26, 62, 36],
       [28, 63, 24],
       [31, 55, 23],
       [31, 34, 30],
       [29, 23, 43],
       [28, 49, 44],
       [27, 63, 34],
       [31, 63, 24],
       [30, 54, 27],
       [30, 45, 36],
       [27, 22, 43],
       [29, 45, 43],
       [31, 59, 31],
       [30, 63, 23],
       [32, 54, 22],
       [30, 44, 35],
       [29, 29, 44],
       [27, 47, 42],
       [29, 63, 25],
       [36, 63, 23],
       [27, 48, 36],
       [30, 35, 40],
       [26, 44, 44],
       [26, 63, 28],
       [36, 63, 23],
       [37, 43, 29],
       [33, 33, 40],
       [27, 49, 43],
       [31, 50, 42],
       [32, 63, 22],
       [36, 61, 22],
       [33, 35, 32],
       [32, 28, 43],
       [28, 50, 43],
       [31, 63, 25],
       [38, 62, 23],
       [33, 35, 35],
       [34, 24, 41]])

In [42]:
len(segment[1])

200

In [50]:
segment[1][100][0]

26

In [43]:
segment[2]

array([[26, 49, 31],
       [27, 50, 32],
       [26, 51, 31],
       [25, 51, 32],
       [23, 52, 32],
       [21, 53, 33],
       [21, 52, 32],
       [22, 53, 31],
       [21, 53, 31],
       [21, 52, 31],
       [19, 52, 29],
       [17, 52, 31],
       [17, 52, 29],
       [16, 50, 31],
       [18, 50, 30],
       [21, 51, 32],
       [22, 54, 33],
       [24, 53, 34],
       [25, 52, 36],
       [26, 53, 36],
       [26, 55, 36],
       [27, 49, 38],
       [27, 50, 35],
       [28, 51, 37],
       [26, 51, 34],
       [25, 51, 34],
       [27, 52, 33],
       [27, 54, 33],
       [27, 55, 32],
       [30, 54, 36],
       [30, 46, 34],
       [29, 44, 30],
       [33, 33, 36],
       [33, 44, 37],
       [33, 53, 32],
       [26, 63, 25],
       [23, 62, 22],
       [30, 40, 28],
       [25, 31, 36],
       [29, 53, 41],
       [32, 61, 30],
       [32, 63, 21],
       [25, 54, 25],
       [27, 34, 31],
       [28, 53, 41],
       [33, 53, 35],
       [29, 63, 25],
       [29, 57, 20],
       [31, 38, 25],
       [27, 29, 39],
       [30, 47, 42],
       [27, 63, 28],
       [28, 63, 20],
       [26, 49, 26],
       [29, 40, 34],
       [28, 28, 44],
       [29, 46, 43],
       [28, 63, 24],
       [33, 62, 22],
       [29, 41, 29],
       [30, 28, 39],
       [25, 49, 44],
       [26, 62, 36],
       [28, 63, 24],
       [31, 55, 23],
       [31, 34, 30],
       [29, 23, 43],
       [28, 49, 44],
       [27, 63, 34],
       [31, 63, 24],
       [30, 54, 27],
       [30, 45, 36],
       [27, 22, 43],
       [29, 45, 43],
       [31, 59, 31],
       [30, 63, 23],
       [32, 54, 22],
       [30, 44, 35],
       [29, 29, 44],
       [27, 47, 42],
       [29, 63, 25],
       [36, 63, 23],
       [27, 48, 36],
       [30, 35, 40],
       [26, 44, 44],
       [26, 63, 28],
       [36, 63, 23],
       [37, 43, 29],
       [33, 33, 40],
       [27, 49, 43],
       [31, 50, 42],
       [32, 63, 22],
       [36, 61, 22],
       [33, 35, 32],
       [32, 28, 43],
       [28, 50, 43],
       [31, 63, 25],
       [38, 62, 23],
       [33, 35, 35],
       [34, 24, 41],
       [29, 52, 44],
       [31, 63, 25],
       [39, 62, 25],
       [34, 48, 32],
       [29, 27, 41],
       [27, 57, 46],
       [29, 63, 32],
       [36, 63, 28],
       [38, 50, 29],
       [33, 25, 36],
       [27, 52, 41],
       [28, 63, 28],
       [37, 63, 27],
       [35, 54, 31],
       [33, 31, 37],
       [28, 53, 41],
       [28, 58, 32],
       [33, 63, 23],
       [35, 56, 25],
       [26, 37, 35],
       [28, 38, 45],
       [29, 45, 43],
       [34, 63, 24],
       [38, 63, 19],
       [33, 45, 31],
       [30, 27, 42],
       [26, 46, 37],
       [29, 63, 26],
       [35, 62, 24],
       [35, 51, 34],
       [33, 40, 42],
       [31, 51, 44],
       [29, 63, 30],
       [33, 63, 24],
       [32, 49, 29],
       [27, 31, 37],
       [27, 56, 42],
       [29, 61, 31],
       [38, 63, 20],
       [36, 46, 23],
       [31, 27, 34],
       [26, 49, 44],
       [30, 56, 41],
       [33, 63, 23],
       [38, 59, 25],
       [32, 40, 33],
       [30, 27, 41],
       [30, 51, 42],
       [30, 63, 28],
       [35, 63, 25],
       [37, 50, 24],
       [31, 33, 35],
       [28, 36, 40],
       [32, 49, 41],
       [31, 63, 28],
       [37, 63, 28],
       [32, 48, 32],
       [29, 29, 39],
       [27, 54, 41],
       [28, 62, 32],
       [34, 63, 25],
       [36, 55, 29],
       [27, 34, 36],
       [29, 43, 38],
       [30, 52, 40],
       [31, 63, 31],
       [34, 62, 26],
       [28, 44, 29],
       [31, 32, 38],
       [30, 50, 39],
       [31, 58, 32],
       [31, 63, 25],
       [31, 59, 29],
       [28, 47, 32],
       [30, 20, 38],
       [27, 51, 44],
       [26, 61, 33],
       [28, 63, 26],
       [34, 60, 24],
       [29, 42, 34],
       [30, 19, 40],
       [27, 56, 43],
       [25, 63, 29],
       [32, 63, 22],
       [33, 58, 23],
       [34, 42, 30],
       [31, 20, 41],
       [27, 53, 45],
       [28, 63, 29],
       [34, 63, 21],
       [34, 47, 24],
       [33, 39, 33],
       [30, 31, 41],
       [29, 51, 41],
       [30, 63, 27],
       [38, 62, 25],
       [33, 44, 29],
       [32, 29, 33],
       [28, 51, 37],
       [29, 53, 35]])

In [65]:
x_list=[row[0] for row in segment[1]] #The X value in segment 2

In [66]:
x_dataframe = pd.DataFrame(x_list) #convert to dataframe

In [70]:
x_dataframe.std() # column 0 STD

0    4.261193
dtype: float64

In [67]:
segment1 = pd.DataFrame(segment[1])

In [68]:
segment1.std() #return the std for each column

0    4.261193
1    7.595317
2    5.202799
dtype: float64

In [69]:
segment1.mean() # return the mean for each column

0    25.445
1    50.140
2    33.715
dtype: float64